import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — AutoCoach",
  description: "The terms that govern your use of AutoCoach.",
};

const LAST_UPDATED = "June 11, 2026";
const CONTACT_EMAIL = "abhaykerala@gmail.com";

function Section({ n, title, children }: { n: string; title: string; children: React.ReactNode }) {
  return (
    <section className="border-t border-[var(--line-default)] pt-8 pb-10">
      <p className="kicker mb-2">
        {n} / {title.toUpperCase()}
      </p>
      <div className="space-y-4 text-[14px] leading-relaxed text-[var(--fg-secondary)] [&_strong]:text-[var(--fg-primary)] [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:space-y-1.5">
        {children}
      </div>
    </section>
  );
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--bg-base)] text-[var(--fg-primary)]">
      <main className="mx-auto max-w-[720px] px-6 py-16">
        <p className="kicker mb-3">LEGAL / TERMS</p>
        <h1 className="font-display uppercase text-[32px] font-medium tracking-[-0.02em]">
          Terms of Service
        </h1>
        <p className="mt-2 font-mono text-[12px] text-[var(--fg-tertiary)]">
          Last updated: {LAST_UPDATED}
        </p>

        <p className="mt-8 mb-10 text-[14px] leading-relaxed text-[var(--fg-secondary)]">
          These terms govern your use of AutoCoach. By creating an account or using the service you
          agree to them. If you do not agree, do not use AutoCoach.
        </p>

        <Section n="01" title="The service">
          <p>
            AutoCoach turns documents you upload into AI-generated quizzes and tracks your mastery
            over time. The service is provided as-is and may change, be interrupted, or be
            discontinued at any time. Free-tier limits (such as document counts, file sizes, and
            daily quiz quotas) may be adjusted without notice.
          </p>
        </Section>

        <Section n="02" title="Your content">
          <ul>
            <li>
              You keep ownership of documents you upload. You grant us a limited license to store
              and process them (including via third-party AI providers) solely to provide the
              service to you.
            </li>
            <li>
              <strong>Only upload content you have the right to use.</strong> Do not upload
              materials that infringe copyright, contain other people&rsquo;s personal data, or are
              unlawful.
            </li>
          </ul>
        </Section>

        <Section n="03" title="AI-generated content">
          <p>
            Quiz questions, answers, explanations, and grading are generated by AI and{" "}
            <strong>may be inaccurate, incomplete, or misleading</strong>. AutoCoach is a study
            aid, not a source of truth — verify important information against your original
            materials. Do not rely on it for medical, legal, financial, or safety-critical
            decisions.
          </p>
        </Section>

        <Section n="04" title="Acceptable use">
          <ul>
            <li>No attempting to access other users&rsquo; data or probe the service for vulnerabilities without permission.</li>
            <li>No circumventing rate limits, quotas, or usage restrictions (including via multiple accounts).</li>
            <li>No using the service to generate or distribute unlawful or harmful content.</li>
            <li>No scraping, reselling, or white-labeling the service without written permission.</li>
          </ul>
          <p>We may suspend or terminate accounts that violate these terms.</p>
        </Section>

        <Section n="05" title="Account & termination">
          <p>
            You are responsible for safeguarding your account credentials. You may stop using the
            service at any time and request account deletion by emailing{" "}
            <a className="text-[var(--accent-text)]" href={`mailto:${CONTACT_EMAIL}`}>
              {CONTACT_EMAIL}
            </a>
            . We may suspend or terminate accounts for breach of these terms or to protect the
            service.
          </p>
        </Section>

        <Section n="06" title="Disclaimers & liability">
          <p>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
            IMPLIED, INCLUDING FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. TO THE
            MAXIMUM EXTENT PERMITTED BY LAW, OUR TOTAL LIABILITY FOR ANY CLAIM ARISING FROM THE
            SERVICE IS LIMITED TO THE GREATER OF $50 OR THE AMOUNT YOU PAID US IN THE 12 MONTHS
            BEFORE THE CLAIM. WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, OR CONSEQUENTIAL DAMAGES,
            OR FOR LOSS OF DATA.
          </p>
        </Section>

        <Section n="07" title="Privacy">
          <p>
            Our{" "}
            <Link href="/privacy" className="text-[var(--accent-text)]">
              Privacy Policy
            </Link>{" "}
            explains how we handle your data and is part of these terms.
          </p>
        </Section>

        <Section n="08" title="Changes, governing law & contact">
          <p>
            We may update these terms; the date above reflects the latest revision and material
            changes will be announced in the app. Continued use after changes means acceptance.
            These terms are governed by the laws of the operator&rsquo;s jurisdiction, without
            regard to conflict-of-law rules. Questions:{" "}
            <a className="text-[var(--accent-text)]" href={`mailto:${CONTACT_EMAIL}`}>
              {CONTACT_EMAIL}
            </a>
            .
          </p>
        </Section>

        <div className="border-t border-[var(--line-default)] pt-8 flex items-center justify-between">
          <Link
            href="/"
            className="font-mono text-[12px] uppercase tracking-[0.08em] text-[var(--accent-text)] hover:text-[var(--ink)]"
          >
            ← AutoCoach
          </Link>
          <Link
            href="/privacy"
            className="font-mono text-[12px] uppercase tracking-[0.08em] text-[var(--accent-text)] hover:text-[var(--ink)]"
          >
            Privacy Policy →
          </Link>
        </div>
      </main>
    </div>
  );
}
