"""concept mastery phase 2.1

Revision ID: 361a250772af
Revises:
Create Date: 2026-02-04 21:29:24.147501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "361a250772af"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "concepts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("concept_name", sa.Text(), nullable=False),
        sa.Column("concept_description", sa.Text(), nullable=True),
        sa.Column("importance", sa.Text(), server_default="core", nullable=False),
        sa.Column(
            "importance_score",
            sa.Numeric(precision=3, scale=2),
            server_default="0.80",
            nullable=False,
        ),
        sa.Column("parent_concept_id", sa.UUID(), nullable=True),
        sa.Column("chunk_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["parent_concept_id"],
            ["concepts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_concepts_document_id"), "concepts", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_concepts_parent_concept_id"),
        "concepts",
        ["parent_concept_id"],
        unique=False,
    )
    op.create_table(
        "user_concept_mastery",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("concept_id", sa.UUID(), nullable=False),
        sa.Column(
            "mastery_score",
            sa.Numeric(precision=5, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("times_tested", sa.Integer(), server_default="0", nullable=False),
        sa.Column("times_correct", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_tested_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mastered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["concept_id"], ["concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_concept_mastery_concept_id"),
        "user_concept_mastery",
        ["concept_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_concept_mastery_user_id"),
        "user_concept_mastery",
        ["user_id"],
        unique=False,
    )
    op.add_column("documents", sa.Column("ai_title", sa.Text(), nullable=True))
    op.add_column(
        "documents",
        sa.Column("progress_core", sa.Numeric(precision=5, scale=2), nullable=True),
    )
    op.add_column(
        "questions", sa.Column("concept_ids", sa.ARRAY(sa.UUID()), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("questions", "concept_ids")
    op.drop_column("documents", "progress_core")
    op.drop_column("documents", "ai_title")
    op.drop_index(
        op.f("ix_user_concept_mastery_user_id"), table_name="user_concept_mastery"
    )
    op.drop_index(
        op.f("ix_user_concept_mastery_concept_id"), table_name="user_concept_mastery"
    )
    op.drop_table("user_concept_mastery")
    op.drop_index(op.f("ix_concepts_parent_concept_id"), table_name="concepts")
    op.drop_index(op.f("ix_concepts_document_id"), table_name="concepts")
    op.drop_table("concepts")
    # ### end Alembic commands ###
