"""add_user_onboarding

Revision ID: c5f3203596fd
Revises: 2e66f7a2ef8b
Create Date: 2026-02-23 16:33:41.909982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5f3203596fd'
down_revision: Union[str, None] = '2e66f7a2ef8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_onboarding',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('learning_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('study_frequency', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_onboarding')
    # ### end Alembic commands ###

